# Training on Small Dataset

In [1]:
#%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

ratingsTrainSmall = pd.read_csv('comp3208-train-small.csv')
ratingsTrainLarge = pd.read_csv('comp3208-train.csv')
ratingsTestSmall  = pd.read_csv('comp3208-test-small.csv')
ratingsTestLarge  = pd.read_csv('comp3208-test.csv')

ratingsTrainSmall.head()
ratingsTrainLarge.head()
ratingsTestSmall.head()
ratingsTestLarge.head()

C:\Users\Dylan\anaconda3\envs\DissertationProject\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

   1  18953  1252960646
0  1  47984  1252965215
1  1  42356  1252962623
2  1  14254  1252962513
3  1  27049  1252964029
4  2  52513  1453954192

In [2]:
#Misses first row when we do this???
ratingsTrainSmallDataframe=pd.DataFrame(ratingsTrainSmall.values, columns = ["UserID", "ItemID", "Rating", "Timestamp"])
ratingsTrainSmallDataframe.head()

  UserID ItemID Rating   Timestamp
0      1    113    1.5  1252964398
1      1   1876    3.0  1252962541
2      1  15482    4.5  1252962367
3      1   2964    3.5  1252964624
4      1  12098    4.0  1252962957

In [3]:
a = ratingsTrainSmallDataframe.groupby('UserID')['Rating'].count()
top_users = a.sort_values(ascending=False)[:15]

b = ratingsTrainSmallDataframe.groupby('ItemID')['Rating'].count()
top_items = b.sort_values(ascending=False)[:15]

top_ratings = ratingsTrainSmallDataframe.join(top_users, rsuffix='_ratings', how='inner', on='UserID')
top_ratings = top_ratings.join(top_items, rsuffix='_ratings', how='inner', on='ItemID')

pd.crosstab(top_ratings.UserID, top_ratings.ItemID, top_ratings.Rating, aggfunc=np.sum)

ItemID,2964,6354,7895,10522,11010,12098,12793,13152,15482,17070,17753,18844,19454,19596,19608
UserID,,,,,,,,,,,,,,,
22480,1.0,3.0,3.0,1.0,3.5,2.5,2.5,4.0,3.5,NaN,3.0,2.0,NaN,3.0,2.5
30752,5.0,5.0,NaN,5.0,5.0,4.0,5.0,5.0,NaN,5.0,5.0,4.0,5.0,4.0,3.5
43500,3.0,4.0,4.0,NaN,3.0,NaN,3.0,4.0,NaN,4.0,4.0,5.0,4.0,4.0,NaN
61628,3.5,5.0,5.0,3.0,3.5,1.5,3.5,NaN,0.5,4.5,3.5,1.0,5.0,3.0,0.5
68801,3.0,0.5,3.5,1.5,2.0,1.0,1.0,0.5,2.5,2.5,1.5,0.5,NaN,1.5,0.5
76028,4.0,4.0,4.0,4.0,NaN,3.0,3.0,4.5,3.0,4.0,3.0,NaN,4.5,4.0,NaN
98801,3.5,4.5,4.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.5,4.0,4.0,3.5,2.0
105105,3.5,3.5,4.5,4.0,4.0,3.5,4.0,4.0,4.0,4.0,3.5,3.5,4.5,3.0,3.5
139801,2.0,2.0,5.0,5.0,5.0,2.0,5.0,4.0,5.0,5.0,1.0,2.0,2.0,1.0,2.5
155433,4.0,4.0,5.0,4.0,4.0,NaN,4.5,4.0,4.0,3.0,2.5,NaN,3.5,4.0,4.0
209354,4.0,4.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,NaN,4.0,5.0,5.0,4.0,1.0
227344,4.5,5.0,5.0,4.5,4.5,4.0,5.0,5.0,5.0,5.0,4.5,4.0,5.0,4.5,3.0
260258,3.0,3.5,4.0,4.5,3.5,3.5,NaN,4.0,4.0,4.5,3.5,NaN,4.0,3.5,2.5
262819,2.0,4.0,5.0,NaN,5.0,5.0,4.0,5.0,3.0,5.0,NaN,NaN,4.0,4.0,NaN
267813,4.0,5.0,4.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0

In [4]:
user_encoder = LabelEncoder()
ratingsTrainSmallDataframe['UserID'] = user_encoder.fit_transform(ratingsTrainSmallDataframe['UserID'].values)
n_users = ratingsTrainSmallDataframe['UserID'].nunique()

item_encoder = LabelEncoder()
ratingsTrainSmallDataframe['ItemID'] = item_encoder.fit_transform(ratingsTrainSmallDataframe['ItemID'].values)
n_items = ratingsTrainSmallDataframe['ItemID'].nunique()

#ratingsDataframe['Rating'] = ratingsDataframe['Rating'].astype(str).str.replace(r'(\rating', '0')

ratingsTrainSmallDataframe['Rating'] = ratingsTrainSmallDataframe['Rating'].astype(str).str.replace("rating","0")
ratingsTrainSmallDataframe['Rating'] = ratingsTrainSmallDataframe['Rating'].values.astype(np.float32)

min_rating = min(ratingsTrainSmallDataframe['Rating'].values.astype(np.float32))
max_rating = max(ratingsTrainSmallDataframe['Rating'].values.astype(np.float32))

n_users, n_items, min_rating, max_rating

#(671, 9066, 0.5, 5.0)
#(274246, 19807, 0.0, 5.0)

(274246, 19807, 0.0, 5.0)

In [5]:
X = ratingsTrainSmallDataframe[['UserID', 'ItemID']].values
y = ratingsTrainSmallDataframe['Rating'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

#((90003, 2), (10001, 2), (90003,), (10001,))

((8483170, 2), (942575, 2), (8483170,), (942575,))

In [6]:
n_factors = 50
X_train_array = [X_train[:, 0], X_train[:, 1]]
X_test_array = [X_test[:, 0], X_test[:, 1]]

In [7]:
from keras.layers import Add, Activation, Lambda, Input, Embedding
from keras.models import load_model


#earlyStopping = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)
#modelCheckpoint = ModelCheckpoint('bestModel.h5', monitor='val_loss', mode='min',  verbose=1, save_best_only=True)

# load a saved model
#saved_model = load_model('bestModel.h5')


class EmbeddingLayer:
    def __init__(self, n_items, n_factors):
        self.n_items = n_items
        self.n_factors = n_factors
    
    def __call__(self, x):
        x = Embedding(self.n_items,
                      self.n_factors,
                      embeddings_initializer='he_normal',
                      embeddings_regularizer=l2(1e-6))(x)
        x = Reshape((self.n_factors,))(x)
        return x

def RecommenderV2(n_users, n_movies, n_factors, min_rating, max_rating):
    user = Input(shape=(1,))
    u = EmbeddingLayer(n_users, n_factors)(user)
    ub = EmbeddingLayer(n_users, 1)(user)
    
    movie = Input(shape=(1,))
    m = EmbeddingLayer(n_movies, n_factors)(movie)
    mb = EmbeddingLayer(n_movies, 1)(movie)
    x = Dot(axes=1)([u, m])
    x = Add()([x, ub, mb])
    x = Activation('sigmoid')(x)
    x = Lambda(lambda x: x * (max_rating - min_rating) + min_rating)(x)
    model = Model(inputs=[user, movie], outputs=x)
    opt = Adam(lr=0.001)
    model.compile(loss='mean_squared_error', optimizer=opt)
    return model

In [8]:
model = RecommenderV2(n_users, n_items, n_factors, min_rating, max_rating)
model.summary()

NameError: name 'l2' is not defined

In [ ]:
history = model.fit(x=X_train_array,
                    y=y_train,
                    batch_size=50000,
                    epochs=100,
                    verbose=1,
                    validation_data=(X_test_array, y_test),
                    callbacks=[earlyStopping, modelCheckpoint])

# Testing on Small Dataset

In [ ]:
from keras.models import load_model

saved_model = load_model('bestModel.h5')

In [ ]:
# evaluate the model
_, train_acc = saved_model.evaluate(trainX, trainy, verbose=0)
_, test_acc = saved_model.evaluate(testX, testy, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))



(trainX, trainy)

# Training on Large Dataset

# Testing on Large Dataset