In [1]:
#Imports
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from scipy import sparse
#import jovian

In [2]:
# Creates a database, clears if exists and fills with training data
import sqlite3
import codecs
import random

# Connect to database (using sqlite3 lib built into python)
conn = sqlite3.connect( 'comp3208_recommender2.db')

# Read in training data file
readHandle = codecs.open( 'comp3208-train.csv', 'r', 'utf-8', errors = 'replace' )
listLines = readHandle.readlines()
readHandle.close()
    
# Creates a table for training data, deletes all data
c = conn.cursor()
c.execute( 'CREATE TABLE IF NOT EXISTS training_table (UserID INT, ItemID INT, Rating FLOAT, Prediction1 FLOAT, Prediction2 FLOAT)' )
conn.commit()
c.execute( 'DELETE FROM training_table' )
conn.commit()
# Inserts data from csv file into training data table (userid, itemid, rating, timestamp - currently not included)
for strLine in listLines :
    if len(strLine.strip()) > 0 :
        listParts = strLine.strip().split(',')
        allFloats = True
        for part in listParts:
            try:
                float(part)
            except ValueError:
                print("Value error", repr(part))
                allFloats = False
        if allFloats == True:
            if len(listParts) == 4 :
                # Insert training set into table with an initial predicted rating of 0
                c.execute( 'INSERT INTO training_table VALUES (?,?,?,?,?)', (listParts[0], listParts[1], listParts[2], random.random() * 5, random.random() * 5) )
            else :
                raise Exception( 'failed to parse csv : ' + repr(listParts) )
        else:
            allFloats = True
conn.commit()
    
# Creates an index of the user ID and item ID
c.execute( 'CREATE INDEX IF NOT EXISTS training_table_index on training_table (UserID, ItemID)' )
conn.commit()

Value error 'rating'

In [3]:
# Inserts testing data into a table in database

# Reads in data
readHandle = codecs.open( 'comp3208-test.csv', 'r', 'utf-8', errors = 'replace' )
listLines = readHandle.readlines()
readHandle.close()

# Create and clear table for testing data
c2 = conn.cursor()
c2.execute( 'CREATE TABLE IF NOT EXISTS testing_table (UserID INT, ItemID INT, Rating FLOAT, PredRating FLOAT)' )
conn.commit()
c2.execute( 'DELETE FROM testing_table' )
conn.commit()
# Inserts data from csv file into testing data table (userid, itemid, timestamp - currently not used)
for strLine in listLines :
    if len(strLine.strip()) > 0 :
        listParts = strLine.strip().split(',')
        if len(listParts) == 3 :
            # Insert training set into table with a rating and predicted rating of 0
            c2.execute( 'INSERT INTO testing_table VALUES (?,?,?,?)', (listParts[0], listParts[1], 0, 0) )
        else :
            raise Exception( 'failed to parse csv : ' + repr(listParts) )
conn.commit()

In [4]:
# Get all user ID', item ID's and ratings from training table in database, store in pandas dataframe
c.execute('SELECT UserID, ItemID, Rating FROM training_table')
items = []
[items.append([x[0], x[1], x[2]]) for x in c.fetchall()]
ratings_df = pd.DataFrame(items, columns=["UserID", "ItemID", "Rating"])
ratings_df.head()

   UserID  ItemID  Rating
0       1   12793     4.0
1       1   31216     4.0
2       1   38744     3.5
3       1     113     1.5
4       1   33000     3.0

In [5]:
# Get all user ID', item ID's and ratings from testing table in database, store in pandas dataframe
c.execute('SELECT UserID, ItemID, Rating FROM testing_table')
items = []
[items.append([x[0], x[1]]) for x in c.fetchall()]
test_df = pd.DataFrame(items, columns=["UserID", "ItemID"])
test_df.head()

   UserID  ItemID
0       1   18953
1       1   47984
2       1   42356
3       1   14254
4       1   27049

In [31]:
# Output count of each rating 
Counter(ratings_df.Rating)

Counter({4.0: 7024679,
         3.5: 3234206,
         1.5: 419265,
         3.0: 5240313,
         4.5: 2254357,
         2.5: 1305118,
         5.0: 3867596,
         2.0: 1758103,
         1.0: 841828,
         0.5: 420307})

In [32]:
# Show number of ratings made by each user
Counter(ratings_df.groupby(["UserID"]).count()["ItemID"])

Counter({99: 651,
         14: 15492,
         509: 37,
         75: 749,
         74: 771,
         38: 1914,
         25: 2751,
         806: 7,
         15: 13185,
         19: 5470,
         106: 535,
         97: 679,
         333: 82,
         1: 5726,
         122: 413,
         6: 5327,
         17: 6194,
         44: 1470,
         18: 5036,
         62: 949,
         29: 2387,
         79: 713,
         16: 8058,
         36: 1771,
         10: 6102,
         665: 21,
         114: 474,
         316: 81,
         69: 840,
         3: 3606,
         32: 2029,
         5: 7402,
         261: 109,
         133: 355,
         52: 1349,
         24: 2948,
         135: 343,
         9: 4929,
         169: 219,
         233: 146,
         7: 4068,
         42: 1477,
         104: 538,
         1345: 2,
         23: 3093,
         240: 121,
         571: 26,
         134: 356,
         43: 1443,
         241: 148,
         11: 4298,
         81: 657,
         65: 924,
         26: 2561,
         68: 884,
         22: 3234,
         13: 3335,
         4: 4449,
         147: 332,
         116: 424,
         391: 62,
         143: 353,
         2: 4112,
         119: 422,
         64: 927,
         28: 2459,
         95: 960,
         88: 590,
         437: 50,
         207: 174,
         8: 3139,
         131: 384,
         315: 76,
         20: 3862,
         94: 558,
         105: 539,
         115: 461,
         145: 318,
         1196: 3,
         39: 1676,
         127: 382,
         411: 53,
         46: 1349,
         41: 1499,
         58: 1080,
         48: 1445,
         30: 2275,
         21: 3504,
         35: 1850,
         40: 1607,
         31: 2167,
         260: 103,
         56: 1149,
         136: 331,
         190: 301,
         72: 813,
         187: 183,
         54: 1137,
         92: 543,
         440: 39,
         12: 3651,
         698: 13,
         87: 606,
         51: 1270,
         33: 2054,
         605: 17,
         363: 46,
         755: 12,
         66: 963,
         287: 132,
         860: 5,
         303: 79,
         63: 933,
         343: 66,
         283: 90,
         93: 511,
         57: 1224,
         83: 614,
         50: 1301,
         1098: 4,
         84: 634,
         27: 2564,
         59: 1033,
         503: 39,
         60: 995,
         221: 183,
         234: 120,
         110: 507,
         160: 260,
         96: 754,
         346: 74,
         747: 9,
         130: 342,
         85: 648,
         211: 168,
         98: 631,
         463: 34,
         1160: 2,
         243: 142,
         309: 100,
         78: 694,
         45: 1412,
         275: 120,
         336: 78,
         436: 34,
         76: 756,
         102: 530,
         55: 1110,
         180: 214,
         439: 49,
         37: 1755,
         196: 216,
         80: 670,
         210: 167,
         360: 50,
         125: 370,
         164: 261,
         247: 157,
         61: 986,
         90: 564,
         1027: 7,
         176: 217,
         89: 541,
         990: 8,
         174: 205,
         150: 281,
         112: 441,
         263: 106,
         182: 204,
         49: 1371,
         132: 375,
         155: 267,
         121: 399,
         77: 695,
         53: 1207,
         67: 853,
         653: 13,
         832: 11,
         403: 65,
         352: 66,
         166: 234,
         230: 138,
         175: 191,
         34: 1890,
         506: 26,
         91: 528,
         214: 172,
         144: 314,
         47: 1486,
         387: 44,
         253: 109,
         599: 21,
         324: 83,
         535: 31,
         212: 159,
         524: 27,
         367: 63,
         146: 299,
         264: 106,
         178: 206,
         111: 440,
         227: 153,
         159: 242,
         152: 308,
         294: 104,
         586: 22,
         71: 846,
         193: 206,
         128: 381,
         326: 62,
         198: 177,
         199: 184,
         70: 841,
         296: 120,
         86: 618,
         620: 24,
         183: 182,
         1313: 5,
         236: 144,
         142: 315,
         342: 76,
         215: 158,
         129: 354,
         73: 783,
         498: 33,
         100: 562,
         255: 115,
         419: 40,
         189: 184,
         120: 432,
         140: 303,
         344: 73,
         369: 52,
         301: 90,
         781: 6,
         704: 12,
         556: 24,
         776: 13,
         209: 207,
         1275: 3,
         126: 370,
         618: 19,
         162: 242,
         884: 12,
         168: 273,
         284: 102,
         291: 87,
         141: 321,
         299: 96,
         257: 108,
         205: 173,
         792: 12,
         103: 576,
         838: 13,
         308: 84,
         330: 89,
         202: 208,
         286: 129,
         427: 51,
         158: 280,
         101: 543,
         197: 180,
         658: 18,
         563: 27,
         445: 46,
         821: 11,
         358: 56,
         148: 292,
         108: 467,
         206: 197,
         4134: 1,
         317: 69,
         137: 295,
         172: 199,
         703: 14,
         384: 52,
         82: 647,
         194: 213,
         259: 121,
         124: 420,
         237: 143,
         338: 80,
         242: 140,
         527: 37,
         404: 48,
         380: 85,
         246: 119,
         235: 135,
         597: 18,
         458: 37,
         374: 41,
         123: 408,
         109: 491,
         525: 23,
         220: 144,
         335: 90,
         314: 92,
         676: 21,
         249: 129,
         493: 39,
         652: 18,
         705: 15,
         734: 16,
         113: 428,
         663: 10,
         339: 69,
         203: 187,
         420: 45,
         224: 173,
         443: 45,
         715: 15,
         138: 354,
         213: 155,
         107: 475,
         188: 192,
         117: 442,
         484: 40,
         397: 49,
         245: 139,
         297: 91,
         170: 214,
         151: 282,
         204: 200,
         381: 59,
         441: 40,
         149: 275,
         562: 24,
         228: 150,
         313: 83,
         184: 180,
         195: 203,
         529: 25,
         139: 300,
         486: 37,
         279: 84,
         389: 60,
         268: 106,
         409: 55,
         765: 14,
         186: 188,
         429: 35,
         834: 9,
         472: 32,
         435: 45,
         250: 122,
         345: 55,
         370: 51,
         530: 38,
         185: 180,
         580: 30,
         570: 37,
         377: 57,
         402: 49,
         457: 38,
         413: 51,
         718: 7,
         917: 10,
         254: 111,
         328: 76,
         347: 51,
         568: 19,
         156: 264,
         650: 20,
         216: 122,
         1007: 3,
         278: 104,
         251: 131,
         167: 229,
         674: 21,
         513: 25,
         350: 64,
         724: 10,
         319: 99,
         200: 194,
         606: 21,
         504: 30,
         337: 73,
         218: 154,
         625: 18,
         587: 19,
         491: 34,
         407: 34,
         293: 98,
         181: 185,
         802: 14,
         225: 151,
         173: 217,
         311: 94,
         281: 91,
         157: 280,
         978: 7,
         797: 10,
         153: 268,
         222: 142,
         355: 63,
         154: 282,
         256: 119,
         752: 14,
         756: 10,
         348: 74,
         267: 104,
         911: 7,
         421: 53,
         1579: 3,
         398: 38,
         1024: 8,
         773: 17,
         258: 116,
         510: 36,
         290: 91,
         318: 80,
         425: 42,
         1291: 3,
         462: 46,
         375: 50,
         273: 103,
         368: 65,
         305: 85,
         394: 51,
         392: 57,
         702: 15,
         321: 76,
         285: 142,
         701: 16,
         118: 409,
         232: 141,
         288: 103,
         768: 10,
         805: 9,
         542: 28,
         426: 46,
         1781: 1,
         1598: 3,
         356: 59,
         331: 81,
         383: 60,
         2334: 2,
         526: 28,
         778: 16,
         1081: 6,
         366: 58,
         617: 16,
         2198: 1,
         516: 34,
         219: 175,
         519: 32,
         1453: 4,
         787: 14,
         379: 68,
         274: 104,
         238: 154,
         393: 59,
         559: 21,
         551: 29,
         177: 180,
         495: 37,
         306: 99,
         252: 127,
         361: 68,
         476: 36,
         408: 55,
         192: 220,
         887: 10,
         736: 21,
         720: 11,
         716: 10,
         438: 43,
         820: 9,
         373: 46,
         998: 8,
         165: 256,
         282: 94,
         201: 187,
         351: 69,
         163: 271,
         536: 30,
         766: 16,
         515: 21,
         731: 16,
         1100: 5,
         208: 157,
         1178: 4,
         1701: 1,
         557: 17,
         610: 20,
         508: 21,
         817: 9,
         340: 64,
         400: 52,
         1348: 4,
         1071: 7,
         1010: 6,
         298: 97,
         621: 14,
         1407: 2,
         659: 18,
         179: 209,
         494: 27,
         231: 140,
         464: 31,
         385: 54,
         161: 254,
         292: 104,
         769: 14,
         271: 98,
         332: 67,
         322: 67,
         312: 74,
         349: 67,
         354: 62,
         575: 29,
         244: 134,
         461: 48,
         417: 47,
         576: 27,
         473: 27,
         741: 9,
         229: 103,
         1239: 6,
         450: 34,
         868: 10,
         607: 21,
         647: 14,
         266: 110,
         1073: 5,
         637: 13,
         856: 7,
         327: 68,
         470: 33,
         572: 31,
         269: 103,
         353: 60,
         574: 27,
         334: 65,
         490: 34,
         855: 16,
         466: 30,
         359: 57,
         396: 59,
         365: 77,
         1337: 5,
         566: 14,
         633: 17,
         988: 8,
         1219: 4,
         239: 140,
         405: 50,
         608: 20,
         710: 19,
         609: 13,
         794: 17,
         2368: 1,
         262: 110,
         226: 120,
         300: 90,
         310: 82,
         632: 23,
         272: 102,
         1285: 5,
         171: 221,
         217: 154,
         307: 90,
         1677: 2,
         511: 38,
         520: 34,
         430: 41,
         1091: 3,
         478: 42,
         265: 125,
         479: 39,
         728: 16,
         388: 48,
         320: 78,
         900: 6,
         465: 30,
         1577: 2,
         657: 13,
         302: 81,
         810: 12,
         553: 28,
         819: 9,
         1149: 7,
         323: 71,
         558: 28,
         1243: 7,
         1428: 2,
         922: 7,
         390: 63,
         679: 21,
         740: 14,
         471: 20,
         341: 73,
         1623: 1,
         751: 12,
         376: 56,
         382: 62,
         191: 227,
         629: 28,
         1460: 2,
         522: 33,
         789: 7,
         1261: 3,
         1018: 8,
         968: 11,
         459: 37,
         760: 15,
         2588: 1,
         454: 34,
         223: 182,
         372: 43,
         1124: 4,
         561: 27,
         364: 65,
         648: 14,
         480: 35,
         447: 28,
         460: 41,
         276: 88,
         951: 7,
         709: 9,
         1171: 7,
         1488: 4,
         399: 58,
         1200: 1,
         782: 10,
         1206: 4,
         602: 21,
         613: 26,
         692: 17,
         488: 23,
         325: 80,
         905: 10,
         894: 5,
         567: 26,
         1214: 5,
         497: 36,
         830: 14,
         959: 6,
         656: 13,
         735: 7,
         416: 46,
         1090: 6,
         1126: 8,
         816: 8,
         475: 72,
         1714: 1,
         248: 93,
         1177: 7,
         1281: 2,
         1042: 8,
         1203: 2,
         329: 78,
         1367: 3,
         863: 11,
         434: 35,
         680: 17,
         406: 45,
         739: 16,
         517: 30,
         681: 12,
         1270: 2,
         432: 52,
         1524: 2,
         415: 42,
         1220: 3,
         1162: 4,
         444: 36,
         410: 56,
         890: 10,
         552: 29,
         615: 17,
         538: 25,
         598: 16,
         1028: 8,
         585: 25,
         448: 35,
         418: 50,
         492: 32,
         500: 30,
         722: 16,
         395: 49,
         963: 7,
         582: 16,
         482: 31,
         449: 34,
         521: 38,
         588: 19,
         523: 35,
         433: 44,
         1408: 2,
         1435: 2,
         531: 29,
         270: 92,
         1201: 3,
         371: 66,
         431: 50,
         746: 12,
         496: 35,
         697: 17,
         1692: 1,
         537: 33,
         684: 11,
         687: 9,
         1276: 5,
         807: 10,
         876: 7,
         764: 14,
         1344: 5,
         798: 12,
         1188: 5,
         1928: 3,
         528: 26,
         1454: 4,
         869: 7,
         937: 5,
         280: 88,
         569: 13,
         560: 27,
         763: 9,
         1801: 3,
         468: 33,
         446: 48,
         477: 52,
         2295: 1,
         1143: 3,
         995: 10,
         2701: 1,
         452: 27,
         1674: 2,
         295: 105,
         661: 12,
         678: 12,
         1590: 3,
         712: 11,
         767: 12,
         596: 24,
         641: 16,
         694: 12,
         1493: 2,
         289: 98,
         499: 38,
         277: 101,
         1305: 4,
         771: 13,
         424: 32,
         4789: 1,
         928: 8,
         1413: 2,
         584: 19,
         898: 5,
         2186: 1,
         1137: 6,
         412: 40,
         1005: 8,
         642: 20,
         532: 15,
         660: 12,
         1485: 5,
         1350: 8,
         683: 14,
         1053: 8,
         1057: 5,
         1036: 3,
         742: 14,
         540: 24,
         812: 9,
         672: 13,
         1336: 6,
         919: 8,
         878: 5,
         304: 80,
         422: 50,
         626: 18,
         502: 35,
         1148: 6,
         414: 35,
         1151: 6,
         474: 38,
         600: 18,
         623: 19,
         880: 9,
         2835: 1,
         1641: 2,
         686: 17,
         753: 10,
         948: 10,
         1013: 6,
         467: 30,
         611: 16,
         1063: 7,
         675: 15,
         931: 7,
         589: 21,
         1382: 2,
         614: 19,
         691: 21,
         546: 31,
         920: 8,
         1696: 2,
         737: 9,
         748: 16,
         639: 12,
         944: 7,
         1048: 6,
         992: 9,
         577: 23,
         902: 7,
         1062: 5,
         1066: 7,
         1895: 1,
         708: 15,
         695: 15,
         635: 9,
         545: 28,
         669: 18,
         362: 65,
         1247: 5,
         729: 8,
         804: 10,
         1663: 2,
         852: 11,
         1302: 3,
         423: 38,
         579: 27,
         1422: 3,
         2646: 1,
         685: 18,
         4078: 1,
         809: 14,
         593: 16,
         774: 8,
         1121: 4,
         668: 21,
         401: 49,
         1393: 1,
         1650: 2,
         469: 31,
         969: 13,
         670: 16,
         2184: 1,
         785: 13,
         1854: 3,
         634: 20,
         1580: 2,
         544: 26,
         893: 16,
         483: 32,
         1384: 1,
         1425: 4,
         512: 34,
         534: 26,
         428: 41,
         636: 11,
         603: 22,
         507: 26,
         925: 8,
         505: 31,
         378: 53,
         453: 37,
         1864: 1,
         573: 13,
         550: 23,
         689: 13,
         564: 25,
         1555: 3,
         1918: 1,
         1546: 1,
         631: 21,
         1629: 3,
         601: 22,
         638: 13,
         1311: 3,
         831: 6,
         2031: 1,
         1044: 3,
         1144: 1,
         1265: 2,
         666: 18,
         757: 19,
         612: 27,
         1651: 2,
         1213: 5,
         997: 9,
         518: 26,
         1223: 1,
         1038: 5,
         1490: 1,
         501: 23,
         874: 8,
         744: 10,
         645: 19,
         514: 27,
         758: 12,
         1346: 3,
         1826: 3,
         2341: 1,
         993: 5,
         888: 8,
         1409: 2,
         749: 16,
         1484: 2,
         1097: 4,
         583: 22,
         549: 30,
         1156: 3,
         677: 16,
         451: 37,
         1602: 2,
         1522: 3,
         843: 6,
         719: 12,
         985: 3,
         1114: 5,
         4049: 1,
         1434: 3,
         1645: 3,
         904: 4,
         723: 9,
         1070: 6,
         595: 17,
         555: 30,
         1260: 7,
         862: 9,
         1403: 2,
         604: 12,
         977: 9,
         1554: 2,
         960: 10,
         784: 7,
         1120: 5,
         921: 7,
         1008: 6,
         814: 10,
         2606: 1,
         1082: 6,
         1108: 3,
         1216: 3,
         783: 14,
         622: 17,
         2527: 1,
         1545: 2,
         630: 18,
         1021: 9,
         1237: 3,
         5519: 1,
         808: 10,
         673: 22,
         891: 7,
         565: 20,
         923: 7,
         1489: 2,
         721: 23,
         1020: 7,
         690: 12,
         2992: 1,
         1152: 4,
         640: 21,
         455: 30,
         386: 54,
         481: 35,
         1228: 5,
         2122: 1,
         850: 8,
         1064: 5,
         548: 26,
         456: 41,
         489: 33,
         885: 8,
         1083: 5,
         1583: 2,
         1334: 3,
         725: 12,
         1657: 3,
         1089: 6,
         1029: 3,
         1157: 2,
         594: 16,
         1494: 2,
         646: 12,
         1476: 1,
         1040: 8,
         643: 21,
         1052: 6,
         700: 16,
         1047: 5,
         1377: 4,
         1080: 3,
         1532: 2,
         578: 11,
         1017: 5,
         357: 71,
         1754: 1,
         1571: 2,
         1139: 3,
         1209: 3,
         844: 5,
         926: 7,
         1284: 3,
         1065: 7,
         627: 15,
         ...})

In [33]:
# Show average number of ratings per user
np.mean(ratings_df.groupby(["UserID"]).count()["ItemID"])

93.18173528892031

In [6]:
# FOR TESTING: Split into training and testing
train_df, test_df = train_test_split(ratings_df, test_size=0.2)

# Reset index values of train and test set
train_df = train_df.reset_index()[["UserID", "ItemID", "Rating"]]
test_df = test_df.reset_index()[["UserID", "ItemID", "Rating"]]

In [34]:
# Reset indexes of training and testing data
train_df = ratings_df.reset_index()[["UserID", "ItemID", "Rating"]]
test_df = test_df.reset_index()[["UserID", "ItemID"]]

In [7]:
# Encode columns to have continuous IDs
def encode_column(column):
    keys = column.unique()
    key_to_id = {key:idx for idx,key in enumerate(keys)}
    return key_to_id, np.array([key_to_id[x] for x in column]), len(keys)

In [8]:
# Encode the whole dataframe to have continuous IDs
def encode_df(rate_df):
    movie_ids, rate_df["ItemID"], num_movies = encode_column(rate_df["ItemID"])
    user_ids, rate_df["UserID"], num_users = encode_column(rate_df["UserID"])
    return rate_df, num_users, num_movies, user_ids, movie_ids

In [9]:
# Output number of users and movies after encoding
rate_df, num_users, num_movies, user_ids, movie_ids = encode_df(train_df)
print("Number of users:", num_users)
print("Number of movies:", num_movies)
rate_df.head()

Number of users: 281631
Number of movies: 51045

   UserID  ItemID  Rating
0       0       0     4.0
1       1       1     3.0
2       2       2     3.0
3       3       3     3.0
4       4       4     5.0

In [10]:
# Creates a random matrix with shape (n,K)
def create_embeddings(n, K):
    return 11*np.random.random((n,K)) / K

In [11]:
# Creates a sparse utilitiy matrix
def create_sparse_matrix(df, rows, cols, column_name="Rating"):
    return sparse.csc_matrix((df[column_name].values,(df["UserID"].values, df["ItemID"].values)), shape=(rows, cols))

In [12]:
rate_df, num_users, num_movies, user_ids, movie_ids = encode_df(train_df)
Y = create_sparse_matrix(rate_df, num_users, num_movies)

In [13]:
# Makes the prediction using elementwise multiplication to avoid making a dense matrix
def predict(df, emb_user, emb_movie):
    df["Prediction"] = np.sum(np.multiply(emb_movie[df["ItemID"]],emb_user[df["UserID"]]), axis=1)
    #new_pred = []
    #for pred in df["Prediction"]:
    #    if pred > 5: 
    #        new_pred.append(5)
    #    else:
    #        new_pred.append(pred)
    #df["Prediction"] = new_pred
    #df["Prediction"] = [round(item*2)/2 for item in df["Prediction"]]
    return df

In [15]:
lmbda = 0.0003

In [16]:
# Calculates the cost (MSE)
def cost(df, emb_user, emb_movie):
    Y = create_sparse_matrix(df, emb_user.shape[0], emb_movie.shape[0])
    predicted = create_sparse_matrix(predict(df, emb_user, emb_movie), emb_user.shape[0], emb_movie.shape[0], 'Prediction')
    return np.sum((Y-predicted).power(2))/df.shape[0]

In [17]:
# Calculates the gradient for the user and movie embeddings
def gradient(df, emb_user, emb_movie):
    Y = create_sparse_matrix(df, emb_user.shape[0], emb_movie.shape[0])
    predicted = create_sparse_matrix(predict(df, emb_user, emb_movie), emb_user.shape[0], emb_movie.shape[0], 'Prediction')
    delta =(Y-predicted)
    grad_user = (-2/df.shape[0])*(delta*emb_movie) + 2*lmbda*emb_user
    grad_movie = (-2/df.shape[0])*(delta.T*emb_user) + 2*lmbda*emb_movie
    return grad_user, grad_movie

In [86]:
# Calculates the gradient descent with the momentum beta
def gradient_descent(df, emb_user, emb_movie, iterations=2000, learning_rate=0.01, df_val=None):
    Y = create_sparse_matrix(df, emb_user.shape[0], emb_movie.shape[0])
    beta = 0.9
    grad_user, grad_movie = gradient(df, emb_user, emb_movie)
    v_user = grad_user
    v_movie = grad_movie
    for i in range(iterations):
        grad_user, grad_movie = gradient(df, emb_user, emb_movie)
        v_user = beta*v_user + (1-beta)*grad_user
        v_movie = beta*v_movie + (1-beta)*grad_movie
        emb_user = emb_user - learning_rate*v_user
        emb_movie = emb_movie - learning_rate*v_movie
        if(not (i+1)%50):
            print("\niteration", i+1, ":")
            print("train mse:",  cost(df, emb_user, emb_movie))
            if df_val is not None:
                print("validation mse:",  cost(df_val, emb_user, emb_movie))
    return emb_user, emb_movie

In [85]:
emb_user = create_embeddings(num_users, 3)
emb_movie = create_embeddings(num_movies, 3)
emb_user, emb_movie = gradient_descent(rate_df, emb_user, emb_movie, iterations=450, learning_rate=1)

<ipython-input-13-e4dc2b150fcf>:3: RuntimeWarning: overflow encountered in multiply
  df["Prediction"] = np.sum(np.multiply(emb_movie[df["ItemID"]],emb_user[df["UserID"]]), axis=1)
C:\Users\BobsH\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

KeyboardInterrupt:

# Predictions

In [20]:
# Removes data not seen before
def encode_new_data(valid_df, user_ids, movie_ids):
    df_val_chosen = valid_df["ItemID"].isin(movie_ids.keys()) & valid_df["UserID"].isin(user_ids.keys())
    #[print(x) for x=false in df_val_chosen]
    #for i in range(len(df_val_chosen)):
        #if df_val_chosen[i] == False:
            #print(i)
    #print(df_val_chosen)
    valid_df = valid_df[df_val_chosen]
    #print(valid_df)
    valid_df["ItemID"] = np.array([movie_ids[x] for x in valid_df["ItemID"]])
    valid_df["UserID"] = np.array([user_ids[x] for x in valid_df["UserID"]])
    return valid_df

In [21]:
def unknown_data(invalid_df, user_ids, movie_ids):
    df_not_chosen = invalid_df["ItemID"].isin(movie_ids.keys()) & invalid_df["UserID"].isin(user_ids.keys())
    #print(df_not_chosen.keys())
    invalid_df = invalid_df[np.logical_not(df_not_chosen)]
    invalid_df["ItemID"] = np.array([test_movie_ids[x] for x in invalid_df["ItemID"]])
    invalid_df["UserID"] = np.array([test_user_ids[x] for x in invalid_df["UserID"]])
    return valid_df

In [22]:
print("Before encoding:", test_df.shape)
valid_df = encode_new_data(test_df, user_ids, movie_ids)
invalid_df = unknown_data(test_df, user_ids, movie_ids)
print("After encoding:", valid_df.shape)
print("Unknown shape:", invalid_df.shape)

Before encoding: (5273155, 3)

<ipython-input-20-952e4b072923>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valid_df["ItemID"] = np.array([movie_ids[x] for x in valid_df["ItemID"]])
<ipython-input-20-952e4b072923>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valid_df["UserID"] = np.array([user_ids[x] for x in valid_df["UserID"]])

NameError: name 'test_movie_ids' is not defined

In [41]:
en_test_df, num_test_users, num_test_movies, test_user_ids, test_movie_ids = encode_df(test_df)

In [23]:
print("After encoding:", valid_df.shape)

After encoding: (4965355, 3)

In [ ]:
invalid_df = []
invalid_df["UserID"] = np.array(test_user_ids[x] for x in )

In [61]:
new_df = predict(valid_df, emb_user, emb_movie)

<ipython-input-48-e4dc2b150fcf>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Prediction"] = np.sum(np.multiply(emb_movie[df["ItemID"]],emb_user[df["UserID"]]), axis=1)

In [49]:
# Output the 70-80th columns of predicted data
valid_df[6010:7720].head()

      UserID  ItemID  Rating  Prediction
6010    5719    1721     5.0    3.514622
6011    5720     601     5.0    1.215980
6012    5721     318     4.0    4.552377
6013    5722     948     3.0    5.102184
6014    5723     654     4.5    2.662180

In [27]:
# Calculates the MSE o the training and testing data
train_mse = cost(train_df, emb_user, emb_movie)
val_mse = cost(valid_df, emb_user, emb_movie)
print(train_mse, val_mse)

<ipython-input-13-e4dc2b150fcf>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Prediction"] = np.sum(np.multiply(emb_movie[df["ItemID"]],emb_user[df["UserID"]]), axis=1)

3.815652131050122 13.66687418302316

In [25]:
new_pred = []
for pred in valid_df["Prediction"]:
    if pred > 5: 
        new_pred.append(5)
    else:
        new_pred.append(pred)
print(new_pred[7040:7044])
valid_df["Prediction"] = new_pred

[5, 5, 4.55944452289862, 3.6378932723426187]

<ipython-input-25-3d93894a5518>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valid_df["Prediction"] = new_pred

In [26]:
new_pred = []
for pred in valid_df["Prediction"]: 
    new_pred.append(round(pred*2)/2)
print(new_pred[7040:7044])
valid_df["Prediction"] = new_pred

[5.0, 5.0, 4.5, 3.5]

<ipython-input-26-571876355b29>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valid_df["Prediction"] = new_pred

In [ ]:
for item in valid_df:
    c.execute('INSERT INTO testing_table_2 VALUES (?,?,?)', (valid_df["UserID"], listParts["ItemID"], listParts["Prediction"]) )

In [57]:
forSQL = []
for i in :
    print(i)
    forSQL.append((valid_df["Prediction"][i], valid_df["UserID"][i], valid_df["ItemID"][i]))

0
1
2

KeyError: 2

In [82]:
records = valid_df.to_records(index=False)
result = list(records)
print(result[60:70])

[(222761, 26361, 4., 3.83868437), (214986, 28862, 4.5, 0.86828588), (262843, 11122, 5., 3.63222815), (1336, 12232, 5., 6.54612788), (220946, 34513, 4., 7.85490807), (34262, 25586, 3., 12.92640097), (26941, 27972, 4., 5.79248552), (272465, 20136, 3.5, 3.28857748), (219439, 9679, 3., 3.74697019), (10720, 27041, 3., 3.90267993)]

In [83]:
forSQL = []
for item in result:
    forSQL.append(item[3], item[0], item[1])

TypeError: append() takes exactly one argument (3 given)

In [59]:
c.executemany('UPDATE testing_table SET PredRating = ? WHERE UserID = ? AND ItemID = ?', valid_df)

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 3, and there are 6 supplied.